"""Fourier Face Camera の設定値を定義する。"""

# カメラ設定
DEFAULT_CAMERA_ID = 0
FALLBACK_FPS = 30

# モデル設定
SELFIE_SEGMENTER_MODEL_PATH = "selfie_segmenter.tflite"
SELFIE_SEGMENTER_MODEL_URL = (
    "https://storage.googleapis.com/mediapipe-models/image_segmenter/"
    "selfie_segmenter/float16/latest/selfie_segmenter.tflite"
)

# 線画設定
DEFAULT_LINE_COLOR_RGB = (0, 255, 255)
DEFAULT_SKETCH_THRESHOLD = 30
DEFAULT_NUM_FREQUENCIES = 30
MIN_CONTOUR_POINTS = 4

# マスク処理設定
ERODE_KERNEL_SIZE = (5, 5)
ERODE_ITERATIONS = 2

# スケッチ抽出設定
CLAHE_CLIP_LIMIT = 2.0
CLAHE_TILE_GRID_SIZE = (8, 8)
BILATERAL_FILTER_DIAMETER = 7
BILATERAL_FILTER_SIGMA_COLOR = 45
BILATERAL_FILTER_SIGMA_SPACE = 45
GAUSSIAN_BLUR_KERNEL_SIZE = (21, 21)
SKETCH_DIVIDE_SCALE = 256
SKETCH_MAX_VALUE = 255
USE_ADAPTIVE_SKETCH_THRESHOLD = True
ADAPTIVE_THRESHOLD_BLOCK_SIZE = 15
ADAPTIVE_THRESHOLD_C = 2
BINARY_DENOISE_MEDIAN_KERNEL_SIZE = 3
BINARY_OPEN_KERNEL_SIZE = (3, 3)
BINARY_OPEN_ITERATIONS = 1
EDGE_SOURCE_BLUR_KERNEL_SIZE = (5, 5)
CANNY_LOW_THRESHOLD = 100
CANNY_HIGH_THRESHOLD = 200
CANNY_AUTO_SIGMA = 0.20
USE_AUTO_CANNY_THRESHOLDS = True
CLOSE_KERNEL_SIZE = (1, 1)
MIN_EDGE_COMPONENT_AREA = 50
MIN_EDGE_COMPONENT_SIZE = 25
USE_TEMPORAL_EDGE_STABILIZATION = True
TEMPORAL_EDGE_DECAY = 0.65
TEMPORAL_EDGE_THRESHOLD = 128
MAX_INNER_CONTOURS = 25
MIN_INNER_CONTOUR_POINTS = 35

# 描画設定
SILHOUETTE_LINE_THICKNESS = 3
INNER_LINE_THICKNESS = 2

# モニター表示設定
MONITOR_WINDOW_NAME = "Fourier Face Camera (Monitor)"
EXIT_KEY = "q"
APP_SHOW_COMPARISON_MONITOR = True
COMPARISON_TILE_SIZE = (320, 240)

# 実行時の初期設定
APP_LINE_COLOR_RGB = (255, 0, 255)
APP_SKETCH_THRESHOLD = 60
